# This is a basic workflow to help you get started with Actions

name: Second

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: hmarr/debug-action@v2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        ref: ${{ github.event.workout_run.head_sha }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world 2!
